export const colors = {
  background: "#f2e3bc",
  text: "#414535",
  header: "#c19875",
  border: "#618985",
  secondary_border: "#38302e",
  secondary_background: "#fef5ef",
  add_message_input_background: "#f2e9e4",
  add_message_form_background: "transparent",
  my_message_background: "#d8f3dc",
  other_message_background: "#ecf8f8",
  sign_in_background: "#ebebd3",
  sign_in_text: "#b38d97",
  sign_in_button_background: "#083d77",
  sign_in_button_title: "#ebebd3",
  sign_in_input_border: "#774936",
};
